"""adiciona capa_url em livros e jogos

Revision ID: 9d2589730106
Revises: 
Create Date: 2026-04-23 15:21:24.450399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2589730106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capa_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capa_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livro', schema=None) as batch_op:
        batch_op.drop_column('capa_url')

    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_column('capa_url')

    # ### end Alembic commands ###
